"""
Scons build file for wiiGesture/src

author : andrea tarocchi
since : 20.10.2008
version : 0.0.1
"""

Import('*') #import of environment from SConstruct script

# per definire un nuovo eseguibile:
# 1) scegliere un nome diverso da quelli presenti che chiameremo NAME
# 2) creare NAME_files = Split("""filei.cpp
#                                   :
#                                   :
#                                   file_n.cpp""") #NAME files
#
# 3) creare:
# NAME_rel = env.Program('NAME', NAME_files)
# cp_NAME_rel = Command("#build/Release/bin/NAME", "NAME", Move("$TARGET", "$SOURCE"))
#
# NAME_dbg = env.Program('NAME', NAME_files)
# cp_NAME_dbg = Command("#build/Debug/bin/NAME", "NAME", Move("$TARGET", "$SOURCE"))
#
# 4) aggiungere in:
# env.Alias('Release', [playerCounter_rel, cp_playerCounter_rel, NAME_rel, cp_NAME_rel])
# env.Alias('Debug', [playerCounter_dbg, cp_playerCounter_dbg, NAME_dbg, cp_NAME_dbg])
#
# ovviamente sostituendo NAME col nome scelto!

wiiGesture_files = Split("""Gaussian_3d.cpp
                            Gaussian_3d_mixture.cpp
                            chmm.cpp
                            hmm.cpp
                            main.cpp
                            sample_3d.cpp
                            gesture.cpp
                            quantizer.cpp""")

discretizzazione_files = Split("""discretizzazione.cpp
                                    gesture.cpp
                                    sample_3d.cpp
                                    quantizer.cpp""")

train_files = Split("""train.cpp
                        hmm.cpp""")

#RELEASE
wiiGesture_rel = env.Program('wiiGesture', wiiGesture_files)
cp_wiiGesture_rel = Command("#bin/Release/wiiGesture", "wiiGesture", Move("$TARGET", "$SOURCE"))

discretizzazione_rel = env.Program('discretizzazione', discretizzazione_files)
cp_discretizzazione_rel = Command("#bin/Release/discretizzazione", "discretizzazione", Move("$TARGET", "$SOURCE"))

train_rel = env.Program('train', train_files)
cp_train_rel = Command("#bin/Release/train", "train", Move("$TARGET", "$SOURCE"))

env.Alias('Release', [wiiGesture_rel, cp_wiiGesture_rel, discretizzazione_rel, cp_discretizzazione_rel, train_rel, cp_train_rel])

#DEBUG
wiiGesture_dbg = env.Program('wiiGesture', wiiGesture_files)
cp_wiiGesture_dbg = Command("#bin/Debug/wiiGesture", "wiiGesture", [Delete("$TARGET"), Move("$TARGET", "$SOURCE")])

discretizzazione_dbg = env.Program('discretizzazione', discretizzazione_files)
cp_discretizzazione_dbg = Command("#bin/Debug/discretizzazione", "discretizzazione", [Delete("$TARGET"), Move("$TARGET", "$SOURCE")])

train_dbg = env.Program('train', train_files)
cp_train_dbg = Command("#bin/Debug/train", "train", [Delete("$TARGET"), Move("$TARGET", "$SOURCE")])

env.Alias('Debug', [wiiGesture_dbg, cp_wiiGesture_dbg, discretizzazione_dbg, cp_discretizzazione_dbg, train_dbg, cp_train_dbg])

Default(None)
